# Generated by Django 3.2.4 on 2021-06-22 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Date_Of_Birth', models.DateField(verbose_name='Date of Birth')),
                ('Password', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill_Type', models.CharField(max_length=24)),
                ('Skill_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cv', models.CharField(max_length=24)),
                ('Cv_Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.profile')),
            ],
        ),
    ]
